AWSTemplateFormatVersion: 2010-09-09

Description: Deploys Amazon Keyspace (for Apache Cassandra) and Tables for Drilling, Reservoir & Production Applications

Parameters:
  OrgName:
    Type: String
    Default: org
    
  ProjectName:
    Type: String
    Default: rt-subsurface-analysis
    
  Environment:
    Type: String
    Default: dev
    
  RegionName:
    Type: String
    Default: us-east-1
    
  KeyspaceName:
    Type: String
    Default: subsurface
  
  KeyspaceTableNameOne:
    Type: String
    Default: drilling
    
  KeyspaceTableNameTwo:
    Type: String
    Default: reservoir
    
  KeyspaceTableNameThree:
    Type: String
    Default: production
    
  KeyspaceNameTagKey:
    Type: String
    Default: name

  KeyspaceTableNameTagKey:
    Type: String
    Default: name
    
  KeyspaceRegionTagKey:
    Type: String
    Default: region

  KeyspaceEnvironmentTagKey:
    Type: String
    Default: environment

  KeyspaceProjectNameTagKey:
    Type: String
    Default: project


  KeyspaceCreatorTagKey:
    Type: String
    Default: creator

  KeyspaceCreatorTagValue:
    Type: String
    Default: creator@domain.com
    
  KeyspaceTableBillingMode:
    Description: ON_DEMAND or PROVISIONED. For PROVISIONED, read & write capacity units must be specified. If ON_DEMAND is specified, capacity units are neglected.
    Type: String
    Default: PROVISIONED
    
  KeyspaceTableBillingModeReadCapacityUnits:
    Type: String
    Default: 1
    
  KeyspaceTableBillingModeWriteCapacityUnits:
    Type: String
    Default: 1
    
  KeyspaceTablePointInTimeRecoveryEnabled:
    Type: String
    Default: false


Resources:
  OrgKeyspace:
    Type: AWS::Cassandra::Keyspace
    Properties:
      KeyspaceName: !Sub ${KeyspaceName}
      Tags:
        - Key: !Sub ${KeyspaceNameTagKey}
          Value: !Sub ${OrgName}-${Environment}-${KeyspaceName}
        - Key: !Sub ${KeyspaceRegionTagKey}
          Value: !Sub ${RegionName}
        - Key: !Sub ${KeyspaceEnvironmentTagKey}
          Value: !Sub ${Environment}
        - Key: !Sub ${KeyspaceProjectNameTagKey}
          Value: !Sub ${ProjectName}
        - Key: !Sub ${KeyspaceCreatorTagKey}
          Value: !Sub ${KeyspaceCreatorTagValue}
   
  OrgTableOne:
    DependsOn:
    - OrgKeyspace
    Type: AWS::Cassandra::Table
    Properties:
      KeyspaceName: !Sub ${KeyspaceName}
      TableName: !Sub ${KeyspaceTableNameOne}
      PartitionKeyColumns:
      - ColumnName: date_utc
        ColumnType: DATE
      ClusteringKeyColumns:
      - Column:
          ColumnName: id
          ColumnType: TIMEUUID
        OrderBy: DESC
      RegularColumns:
      # time (utc)
      - ColumnName: time_utc
        ColumnType: TIMESTAMP
      # drill string data from regular drilling operation (drill string-related)
      - ColumnName: rop_fph
        ColumnType: DECIMAL
      - ColumnName: rpm_rpm
        ColumnType: DECIMAL
      - ColumnName: spp_psi
        ColumnType: DECIMAL
      - ColumnName: dwob_lb
        ColumnType: DECIMAL
      - ColumnName: swob_lb
        ColumnType: DECIMAL
      - ColumnName: tqr_lbft
        ColumnType: DECIMAL
      - ColumnName: bha_type
        ColumnType: TEXT
      # mud data from regular drilling operation (mud-related)
      - ColumnName: mud_weight_sg
        ColumnType: DECIMAL
      - ColumnName: mud_plastic_visc_cp
        ColumnType: DECIMAL
      - ColumnName: mud_yield_point_lb_per_100ft_sq
        ColumnType: DECIMAL
      - ColumnName: mud_flow_rate_gpm
        ColumnType: DECIMAL
      # mwd/lwd data (measured or calculated) from downhole MWD/LWD tool measurements
      - ColumnName: tvd_ft
        ColumnType: DECIMAL
      - ColumnName: md_ft
        ColumnType: DECIMAL
      - ColumnName: inc_deg
        ColumnType: DECIMAL
      - ColumnName: azim_deg
        ColumnType: DECIMAL
      - ColumnName: dogleg_deg_per_100ft
        ColumnType: DECIMAL
      - ColumnName: caliper_hole_size_inches
        ColumnType: DECIMAL
      - ColumnName: gr_api
        ColumnType: DECIMAL
      - ColumnName: deep_resistivity_ohm_m
        ColumnType: DECIMAL
      - ColumnName: shock_g
        ColumnType: DECIMAL
      - ColumnName: dtemp_deg_c
        ColumnType: DECIMAL
      # event data from MWD/LWD tool measurements and other sources
      - ColumnName: is_vibration
        ColumnType: BOOLEAN
      - ColumnName: is_kick
        ColumnType: BOOLEAN
      - ColumnName: is_stuckpipe
        ColumnType: BOOLEAN
      BillingMode:
        Mode: !Sub ${KeyspaceTableBillingMode}
        ProvisionedThroughput:
          ReadCapacityUnits: !Sub ${KeyspaceTableBillingModeReadCapacityUnits}
          WriteCapacityUnits: !Sub ${KeyspaceTableBillingModeWriteCapacityUnits}
      PointInTimeRecoveryEnabled: !Sub ${KeyspaceTablePointInTimeRecoveryEnabled}
      Tags:
        - Key: !Sub ${KeyspaceTableNameTagKey}
          Value: !Sub ${OrgName}-${Environment}-${KeyspaceTableNameOne}
        - Key: !Sub ${KeyspaceRegionTagKey}
          Value: !Sub ${RegionName}
        - Key: !Sub ${KeyspaceEnvironmentTagKey}
          Value: !Sub ${Environment}
        - Key: !Sub ${KeyspaceProjectNameTagKey}
          Value: !Sub ${ProjectName}
        - Key: !Sub ${KeyspaceCreatorTagKey}
          Value: !Sub ${KeyspaceCreatorTagValue}

  OrgTableTwo:
    DependsOn:
    - OrgKeyspace
    Type: AWS::Cassandra::Table
    Properties:
      KeyspaceName: !Sub ${KeyspaceName}
      TableName: !Sub ${KeyspaceTableNameTwo}
      PartitionKeyColumns:
      - ColumnName: date_utc
        ColumnType: DATE
      ClusteringKeyColumns:
      - Column:
          ColumnName: id
          ColumnType: TIMEUUID
        OrderBy: DESC
      RegularColumns:
      - ColumnName: time_utc
        ColumnType: TIMESTAMP
      # production from named reservoir
      - ColumnName: reservoir_name
        ColumnType: TEXT
      - ColumnName: cum_prod_mm_bbls
        ColumnType: DECIMAL
      - ColumnName: prod_rate_m_bpd
        ColumnType: DECIMAL
      BillingMode:
        Mode: !Sub ${KeyspaceTableBillingMode}
        ProvisionedThroughput:
          ReadCapacityUnits: !Sub ${KeyspaceTableBillingModeReadCapacityUnits}
          WriteCapacityUnits: !Sub ${KeyspaceTableBillingModeWriteCapacityUnits}
      PointInTimeRecoveryEnabled: !Sub ${KeyspaceTablePointInTimeRecoveryEnabled}
      Tags:
        - Key: !Sub ${KeyspaceTableNameTagKey}
          Value: !Sub ${OrgName}-${Environment}-${KeyspaceTableNameTwo}
        - Key: !Sub ${KeyspaceRegionTagKey}
          Value: !Sub ${RegionName}
        - Key: !Sub ${KeyspaceEnvironmentTagKey}
          Value: !Sub ${Environment}
        - Key: !Sub ${KeyspaceProjectNameTagKey}
          Value: !Sub ${ProjectName}
        - Key: !Sub ${KeyspaceCreatorTagKey}
          Value: !Sub ${KeyspaceCreatorTagValue}
          
  OrgTableThree:
    DependsOn:
    - OrgKeyspace
    Type: AWS::Cassandra::Table
    Properties:
      KeyspaceName: !Sub ${KeyspaceName}
      TableName: !Sub ${KeyspaceTableNameThree}
      PartitionKeyColumns:
      - ColumnName: sensor_type
        ColumnType: TEXT
      - ColumnName: location
        ColumnType: TEXT
      - ColumnName: date_utc
        ColumnType: DATE
      ClusteringKeyColumns:
      - Column:
          ColumnName: id
          ColumnType: TIMEUUID
        OrderBy: DESC
      RegularColumns:
      - ColumnName: time_utc
        ColumnType: TIMESTAMP
      - ColumnName: temp_deg_c
        ColumnType: DECIMAL
      - ColumnName: pressure_psi
        ColumnType: DECIMAL
      - ColumnName: rate_mph
        ColumnType: DECIMAL
      - ColumnName: distance_miles
        ColumnType: DECIMAL
      BillingMode:
        Mode: !Sub ${KeyspaceTableBillingMode}
        ProvisionedThroughput:
          ReadCapacityUnits: !Sub ${KeyspaceTableBillingModeReadCapacityUnits}
          WriteCapacityUnits: !Sub ${KeyspaceTableBillingModeWriteCapacityUnits}
      PointInTimeRecoveryEnabled: !Sub ${KeyspaceTablePointInTimeRecoveryEnabled}
      Tags:
        - Key: !Sub ${KeyspaceTableNameTagKey}
          Value: !Sub ${OrgName}-${Environment}-${KeyspaceTableNameThree}
        - Key: !Sub ${KeyspaceRegionTagKey}
          Value: !Sub ${RegionName}
        - Key: !Sub ${KeyspaceEnvironmentTagKey}
          Value: !Sub ${Environment}
        - Key: !Sub ${KeyspaceProjectNameTagKey}
          Value: !Sub ${ProjectName}
        - Key: !Sub ${KeyspaceCreatorTagKey}
          Value: !Sub ${KeyspaceCreatorTagValue}
          
Outputs:
  OrgKeyspaceOutput:
    Description: Keyspace for grouping Tables.
    Value: !Ref OrgKeyspace
    Export:
      Name: !Sub ${OrgName}-${Environment}-${KeyspaceName}
      
  OrgTableOneOutput:
    Description: Table for storing driling data.
    Value: !Ref OrgTableOne
    Export:
      Name: !Sub ${OrgName}-${Environment}-${KeyspaceTableNameOne}
      
  OrgTableTwoOutput:
    Description: Table for storing reservoir data.
    Value: !Ref OrgTableTwo
    Export:
      Name: !Sub ${OrgName}-${Environment}-${KeyspaceTableNameTwo}
      
  OrgTableThreeOutput:
    Description: Table for storing production data.
    Value: !Ref OrgTableThree
    Export:
      Name: !Sub ${OrgName}-${Environment}-${KeyspaceTableNameThree}
