name: CI - AWS-SDK-JS Deploy CFN

on:
  push:
    branches:
    - main
  pull_request:
   # matches pull request for all branches and tag names

jobs:
  aws-sdk-js:
    name: AWS-SDK-JS-Deploy
    runs-on: ubuntu-latest
    env:
      DEV: 'no'
      PROD: 'no'
      DEPLOY: 'no'
      SDK_INIT_DIRECTORY: 'init'
      BASE_DIRECTORY: '/home/runner/work'
      REPO_NAME: ${{ github.event.repository.name }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        shell: bash
 
    steps:
    - uses: actions/checkout@v2
      # note: checkout directory: /home/runner/work/${repo-name}/$${repo-name}
    
    - name: Install Node.js and AWS-SDK Module
      run: |
        # sudo apt-get install npm
        curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash -
        sudo apt-get install -y nodejs
        
        # check versions
        sudo node -v
        sudo npm -v
        
        # create init/base directory & install Node.js module(s)
        sudo mkdir $SDK_INIT_DIRECTORY
        cd $SDK_INIT_DIRECTORY
        sudo npm install @aws-sdk/client-cloudformation

        # show details of the directory content
        sudo df -h
        sudo free -h 
        sudo ls -ltr
        
    - name: Rename Index File - Dev
      if: ${{ env.DEV == 'yes' }}
      run: |
        sudo mv index-dev.js index.js 
        
    - name: Rename Index File - Prod
      if: ${{ env.PROD == 'yes' }}
      run: |
        sudo mv index-prod.js index.js 
        
    - name: AWS SDK DEPLOY CFN YAML/JSON File
      if:  (env.DEPLOY == 'yes') && ( env.DEV == 'yes' || env.PROD == 'yes' )
      run: |
        sudo node index.js
        
