name: CI - AWS-SDK-JS-V3 Deploy CFN

on:
  push:
    branches:
    - main
  pull_request:
   # matches pull request for all branches and tag names

jobs:
  aws-sdk-js-v3:
    name: AWS-SDK-JS-V3-Deploy-CFN
    runs-on: node:alpine3.16 
    #ubuntu-latest
    env:
      DEV: 'yes'
      PROD: 'no'
      DEPLOY: 'yes'
      SDK_INIT_DIRECTORY: 'init'
      BASE_DIRECTORY: '/home/runner/work'
      REPO_NAME: ${{ github.event.repository.name }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        shell: bash
 
    steps:
    - uses: actions/checkout@v2
      # note: checkout directory: /home/runner/work/${repo-name}/$${repo-name}
    
    - name: Install Node.js and CFN-Client-V3 Module
      run: |
        # sudo apt-get install npm
        curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash -
        sudo apt-get install -y nodejs
        
        # check versions
        sudo node -v
        sudo npm -v
        
        # create init/base directory & install Node.js module(s)
        sudo mkdir $SDK_INIT_DIRECTORY
        cd $SDK_INIT_DIRECTORY
        #sudo npm install @aws-sdk/client-cloudformation@3.216.0

        # show details of the directory content
        sudo df -h
        sudo free -h 
        sudo ls -ltr
        
    - name: DEPLOY - Dev
      if:  (env.DEPLOY == 'yes' &&  env.DEV == 'yes')
      run: |
        sudo mv index-dev.js index.js 
        sudo node index.js
        
    - name: DEPLOY - Prod
      if:  (env.DEPLOY == 'yes' && env.PROD == 'yes' )
      run: |
        sudo mv index-prod.js index.js 
        sudo node index.js

