name: CI - AWS-SDK-JS-V3 Deploy CFN

# Option 1: Auto Workflow
#on: 
  # option 1: Auto Workflow
  #push:
  #  branches:
  #  - main
  # pull_request:
  # matches pull request for all branches and tag names
  
# Option 2: Custom (Manual) Workflow
on: 
  workflow_dispatch:
    inputs:
      Run Workflow:
        description: 'Validated'
        default: 'Yes'
        required: true
        options:
        - 'Yes'
        - 'No'
      Tags:
        description: 'AWS-SDK-V3'
        default: true
        required: true
        type: boolean
      Environment:
        description: 'Environment'
        type: environment
        required: true
        
    steps:
    - uses: actions/checkout@v2
      # note: checkout directory: /home/runner/work/${repo-name}/$${repo-name}
      
    - name: Install Node.js & CFN-Client-V3 Module
      run: |
        # install
        sudo apt-get -y update
        curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash -
        sudo apt-get install -y nodejs
        sudo npm install  --prefix $BASE_DIRECTORY/$REPO_NAME/$REPO_NAME @aws-sdk/client-cloudformation
        
        # check versions & show directory's contents and details
        pwd
        sudo node -v
        sudo npm -v
        sudo npm ls
        sudo df -h
        sudo free -h 
        sudo ls -ltr

        
jobs:    

  start:
    name: Deploy-CFN-Start
    runs-on: ubuntu-latest
    environment: starting
    env:
      DEPLOY: 'yes'
    defaults:
      run:
        shell: bash
 
    steps:
    - uses: actions/checkout@v2
      # note: checkout directory: /home/runner/work/${repo-name}/$${repo-name}
      
    - name: DEPLOY - Start
      if:  (env.DEPLOY == 'yes')
      run: |
        pwd
        echo Start of Deployment


  dev:
    # if: ${{ always() }}
    needs: [start]
    name: Deploy-CFN-Dev
    runs-on: ubuntu-latest
    environment: development
    env:
      DEPLOY: 'yes'
      SDK_INIT_DIRECTORY: 'init'
      BASE_DIRECTORY: '/home/runner/work'
      REPO_NAME: ${{ github.event.repository.name }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ENVIRONMENT: ${{ inputs.environment }}
    defaults:
      run:
        shell: bash
 
    steps:
    - uses: actions/checkout@v2
      # note: checkout directory: /home/runner/work/${repo-name}/$${repo-name}
      
    - name: Install Node.js & CFN-Client-V3 Module
      run: |
        # install
        sudo apt-get -y update
        curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash -
        sudo apt-get install -y nodejs
        sudo npm install  --prefix $BASE_DIRECTORY/$REPO_NAME/$REPO_NAME @aws-sdk/client-cloudformation
        
        # check versions & show directory's contents and details
        pwd
        sudo node -v
        sudo npm -v
        sudo npm ls
        sudo df -h
        sudo free -h 
        sudo ls -ltr
         
    - name: Deploy - Dev
      if:  (env.DEPLOY == 'yes' && env.ENVIRONMENT == 'development')
      run: |
        export AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }} 
        export AWS_REGION=${{ env.AWS_REGION }}
        # printenv
        # pwd
        sudo mv index-dev.js index.js 
        sudo node index.js
  
  
  stag:
    #if: ${{ always() }}
    if: ${{ false }}  # disable job
    needs: [start]
    name: Deploy-CFN-Stg
    runs-on: ubuntu-latest
    environment: staging
    env:
      DEPLOY: 'yes'
      SDK_INIT_DIRECTORY: 'init'
      BASE_DIRECTORY: '/home/runner/work'
      REPO_NAME: ${{ github.event.repository.name }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ENVIRONMENT: ${{ inputs.environment }}
    defaults:
      run:
        shell: bash
 
    steps:
    - uses: actions/checkout@v2
      # note: checkout directory: /home/runner/work/${repo-name}/$${repo-name}
      
    - name: Install Node.js & CFN-Client-V3 Module
      run: |
        # install
        sudo apt-get -y update
        curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash -
        sudo apt-get install -y nodejs
        sudo npm install  --prefix $BASE_DIRECTORY/$REPO_NAME/$REPO_NAME @aws-sdk/client-cloudformation
        
        # check versions & show directory's contents and details
        pwd
        sudo node -v
        sudo npm -v
        sudo npm ls
        sudo df -h
        sudo free -h 
        sudo ls -ltr
        
    - name: Deploy - Stag
      if:  (env.DEPLOY == 'yes' && env.ENVIRONMENT == 'staging')
      run: |
        pwd
        sudo mv index-stag.js index.js 
        sudo node index.js
        
        
  prod:
    #if: ${{ always() }}
    if: ${{ false }}  # disable job
    needs: [start]
    name: Deploy-CFN-Prod
    runs-on: ubuntu-latest
    environment: production
    env:
      DEPLOY: 'no'
      SDK_INIT_DIRECTORY: 'init'
      BASE_DIRECTORY: '/home/runner/work'
      REPO_NAME: ${{ github.event.repository.name }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ENVIRONMENT: ${{ inputs.environment }}
    defaults:
      run:
        shell: bash
 
    steps:
    - uses: actions/checkout@v2
      # note: checkout directory: /home/runner/work/${repo-name}/$${repo-name}
      
    - name: Install Node.js & CFN-Client-V3 Module
      run: |
        # install
        sudo apt-get -y update
        curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash -
        sudo apt-get install -y nodejs
        sudo npm install  --prefix $BASE_DIRECTORY/$REPO_NAME/$REPO_NAME @aws-sdk/client-cloudformation
        
        # check versions & show directory's contents and details
        pwd
        sudo node -v
        sudo npm -v
        sudo npm ls
        sudo df -h
        sudo free -h 
        sudo ls -ltr
        
    - name: Deploy - Prod
      if:  (env.DEPLOY == 'yes' && env.ENVIRONMENT == 'production')
      run: |
        pwd
        sudo mv index-prod.js index.js 
        sudo node index.js
        
        
  end:
    #if: ${{ always() }}
    #if: ${{ false }}  # disable job
    needs: [dev, stag, prod]
    name: Deploy-CFN-End
    runs-on: ubuntu-latest
    environment: ending
    env:
      DEPLOY: 'yes'
    defaults:
      run:
        shell: bash
 
    steps:
    - uses: actions/checkout@v2
      # note: checkout directory: /home/runner/work/${repo-name}/$${repo-name}
      
    - name: Deploy - End
      if:  (env.DEPLOY == 'yes')
      run: |
        pwd
        echo End of Deployment
        
